version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.0.0

workflows:
  build_and_deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          repo: "${AWS_RESOURCE_NAME_PREFIX}-repository"
          tag: "${CIRCLE_SHA1}"
          path: "./back"
          filters:
            branches:
              only:
                - main
      - aws-ecr/build-and-push-image/schedule:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          repo: "${AWS_RESOURCE_NAME_PREFIX}-schedule-repository"
          tag: "${CIRCLE_SHA1}-schedule"
          path: "./back"
          dockerfile: "Dockerfile_schedule"
          filters:
            branches:
              only:
                - main
      - aws-ecs/deploy-service-update:
          cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
          container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"
          family: "${AWS_RESOURCE_NAME_PREFIX}-service"
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only:
                - main
      - aws-ecs/deploy-service-update/schedule:
          cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
          container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-schedule-service,tag=${CIRCLE_SHA1}-schedule"
          family: "${AWS_RESOURCE_NAME_PREFIX}-service"
          requires:
            - aws-ecr/build-and-push-image/schedule
          filters:
            branches:
              only:
                - main